#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var tls = require('tls');

var options = {
  pfx: fs.readFileSync(path.join('..', 'auth', 'levelweb.pfx')),
  passphrase: fs.readFileSync(path.join('..', 'auth', 'passphrase.txt')).toString().trim()
};

var client;

function write(json) {
  client.write(JSON.stringify(json) + '\n');
  client.end();
}

client = tls.connect(9097, options, function() {
  write({
    key: "hello",
    value: {
      date: Date.now(),
      foo: "bar"
    }
  });
});