#!/usr/bin/env node

//
// seed the database with random but useful data
//
var moment = require('moment');
var uuid = require('node-uuid');
var net = require('net');

var x = 0;
var today = moment(Date.now());
var time = process.hrtime();

var client = net.connect({ port: 9099 }, function() {

  console.log('Generating and sending data to the server, ^C to interrupt.');

  function write(json) {
    client.write(JSON.stringify(json) + '\n');
  }

  function getRandom(n) {
    return ((Math.random() * (10 || n)) + ++x) / ++x;
  }

  function getIncremented() {
    return ++x;
  }

  setInterval(function() {

    var sessionId = uuid.v4();
    today = today.add('h', ++x);

    write({
      key: 'http-load-time-' + sessionId,
      value: {
        date: moment(today).toString(),
        count: x,
        diff: process.hrtime(time)[0]
      }
    });

    write({
      key: 'tcp-request-' + sessionId,
      value: {
        date: moment(today).toString(),
        count: x,
        diff: process.hrtime(time)[0]
      }
    });

    write({
      key: 'http-request-' + sessionId,
      value: {
        date: moment(today).toString(),
        count: x,
        value: process.hrtime(time)[0]
      }
    });

    write({
      key: 'tcp-request-count-' + today,
      value: {
        date: moment(today).toString(),
        value: getIncremented()
      }
    });

  }, 500);

});
